weights: .\runs\train\myssdayolo\weights\last_teacher.pt
cfg: ''
data: data/yamls_sda/cityscapes_csfoggy.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 10
batch_size: 2
img_size:
- 640
- 640
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: myssdayolo
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: 3
artifact_alias: latest
local_rank: -1
teacher_alpha: 0.99
conf_thres: 0.5
iou_thres: 0.3
max_gt_boxes: 20
lambda_weight: 0.005
consistency_loss: false
alpha_weight: 2.0
student_weight: None
teacher_weight: None
save_dir: runs\train\myssdayolo34
